#===============================================================
# To make this work, install Docker Desktop first from:
# https://docs.docker.com/get-docker
#===============================================================

version: "3"
services:

 lbdbackend:
  container_name: lbdbackend
  restart: always
  build: ..\\..
  ports: 
   - "5000:5000"
  links: 
   - mongo
   - graphdb
 
 mongo:
  container_name: mongo
  image: mongo
  ports:
   - "27018:27017"
 graphdb:
  container_name: graphdb
  image: daschswiss/graphdb:9.0.0-free
  ports:
   - "7201:7200"

   